sudo: false
language: ruby
rvm:
- 2.3.1
before_install: gem install bundler -v 1.13.1
deploy:
  provider: rubygems
  on:
    tags: true
  api_key:
    secure: GunyiKGYQX+bdhJbzw1uaXGnIt0d+N6MO9Gy2Lj+6Gb/vpWSdCW1RBTp37Qm3sKW0JT2rrJ7l4nOb5r/8ydzPQWtOKpDihuzUH7tS5xK+2fDjimyccq0hEos0lyPa9YUb7s7yx0bBBWFflkHUpkwGoaTBmCeTkhDvxsG/TfwjDlRxfOlPS5jItXItkLnKeNQjjcucBF8Z7pF/bx2XelDa4OzYlZVj+NTU5nGy92s4Q4yRrtgVvpExtcoiwymYDawPvePl3olnqilMjuT7Z6J1aFNVtGmEds/uu9KVmwPZtk8lE0CslDLPgI81aKpCWlFsJ4Vxs+Lk6gbGe2CbV1GQRg1wXfy+z6akkGW3bBp8GwKmwLyV/j2tEG1BiOMk/+Ui9BpEb3+XtfvYvtGVaZJHFCCXkZVbtZjX3EXuFYhSjXIz1JY05QZou5bsECJvENwyeSvONJKvIMJFV+A5y2mOe4Q86eOqAfkXlBGD/jKLNHRo1kBotoCNfReDo2/XHM3jeB2T+R+bDT+0kM7OPRpkpfU0Y5hZsuHKbSQq22fs/iWdX0c8xfWWe2hodV+MGq/zftMLNEbZnSKMfvZBExA+3ZrgdjIJLJS5szszMxbC6z+4QlQybx2plPkri4m4Nb10/phN2DI4Lii3ZinREMBr7FkuQNgncA1yXpgmcMhkZc=
