sudo: false
language: ruby
rvm:
- 2.3.1
before_install: gem install bundler -v 1.13.1
deploy:
  provider: rubygems
  on:
    tags: true
  api_key:
    secure: PHvuj0NyV43zwa7/Io/YpgPjU1EK4Tz5dzapI0NoFF8J/Y1H7YAMRNPlSB55vpiKMEshsbrYpz0UNZ66m1Ohr0/ZDa1Hy7RzZCsW17jC5s3G772p69fxt9scGyFv3loB7VcCtJoWKjLNy1s7HQOTR3FUAApvpoj5KeoDUD+d8jBLPQJAguIka7014q4HCgENPXI5tWzlJb4/b+I4b3laWU5NzBy6ucM/XIeE5QoQS7mJuePP51FbJHr/lUc9PMAafmDsB5mQAoS1Etincq4W2cf4DVKeEntdJGntkCQs2llqzXXbMkd4MYcIGvpWRK8Hg5Ny2vBGl0w75ONBo5aMwftbPCeeYN2b1vzy4HRdXqPhEr8bVE6nu2C+7e3OlUZwWdTaIcjINn48Z50d1/R8R7y/we9j3dHkote1okr8xhBNTcp2hPt5GbSkN+mMQAI3iKuHrb6q8H6C71YBbS8H5kZGlaMzYHwzFm60MS+vTnA1q/4sgTLoVlqrLkIfAKumIonwy7g1TdBtfs2cYvxfm2m4oSKAfbAeudC+inRHctwHocT6CvKXx8lUGNcZOR2CAwIEkT7VZ8Z2lLTXnoCBf6adma3urrqnwUdZ9syH6+5L2tNJyNpER0i38MHdWRlJS65SliT7ck2LF5Qth9Uv4uw58EPJnVPC3GMdIKzQZe8=
